#!/bin/sh
# # x-r5rs -- the R5RS lang for x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower plus R5RS,
#   with no launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# The launcher-free boot amalgam carries no path literals and loads from any
# cwd, but lives at share/x/boot/ when installed and build/boot/ in a checkout,
# so probe both, install layout first. lib/x-base.x is not a substitute: it is
# the source entry and opens with a root-relative (include "lib/x-core.x")
# that resolves only from the repo root.
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-r5rs: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-base.x and build/boot/x-base.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# Three requirements on the generated file:
#
# 1. %install-root first. An amalgam carries no include literals, but its
#    deferred `import` forms resolve against the installed tree, which module.x
#    locates from %install-root. x.sh emits the same line ahead of every boot
#    entry.
#
# 2. boot/x-base.x, not a dialect entry. he.x / xe.x / rn.x end by starting a
#    REPL, which would run underneath the suite. x-base.x is launcher-free.
#
# 3. Never re-include a platform module the booted tower already has; on top
#    of a booted tower that crashes with no diagnostic. run.x owns the boot,
#    and nothing under r5rs/ includes anything from the platform.
#
# The bundle root is armed the same way run.x arms it, so `import r5rs/base`
# resolves here as it does at the prompt.
cat > "$OUT" <<EOF
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
(import-path! "$BUNDLE")
(import r5rs/base)
(set! %repl-print %r5rs-repl-print)
EOF
